name: Build version.js based on package file.
on:
  workflow_dispatch: 
  push:
    branches:
      - main
jobs:
  npm:
    name: Use Node to update version.js.
    runs-on: ubuntu-latest
    steps:
    - name: import GitHub actions checkout
      uses: actions/checkout@v3
    - name: import Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: run npm and git
      run: |
        npm i
        date > lastUpdated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "built version.js from build-version_js.yml"
        git push
