name: Log to github-actions.log
on:
  workflow_dispatch: 
    inputs:
      message: 
        description: 'message logged to github-actions.log'
        required: true
        type: string
      logLevel: 
        description: 'logLevel. 1 = INFO, 2 = WARN, 3 = ERROR'
        default: 1
        required: false
        type: number
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: log based on inputs using actions/github-script
      uses: actions/github-script@v1
      with:
        script: |
          const tools = require("logAction")
          tools.logAction("${{ github.event.inputs.message }}", ${{ github.event.inputs.logLevel }}, "CONSOLE")
