name: Log to github-actions.log
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'message logged to github-actions.log'
        required: true
        type: string
      logLevel:
        description: 'logLevel. 1 = INFO, 2 = WARN, 3 = ERROR'
        default: "1"
        required: true
        type: string
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: log based on inputs
      uses: actions/github-script@v6
      with:
        script: |
          var tools = require("./tools.js")
          tools.logAction("${{ github.event.inputs.message }}", ${{ github.event.inputs.logLevel }}, "CONSOLE")
          core.notice("${{ github.event.inputs.message }}")
    - name: push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "logged message init by gh-actions-log"
        git push
