name: Log to github-actions.log
on:
  workflow_dispatch: 
    inputs:
      message: 
        description: 'message logged to github-actions.log'
        required: true
        type: string
      logLevel: 
        description: 'logLevel. 1 = INFO, 2 = WARN, 3 = ERROR'
        default: 1
        required: true
        type: number
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: log based on inputs
      uses: actions/github-script@v6
      with:
        script: |
          function logAction (message, logLevel, source) {
            var fs = require("fs")
            fs.readFile("github-actions.log", (err, buff) => {
              // if any error
              if (err) {
                console.error("[!!! ----- logAction failed ----- !!!]")
                console.error(err);
                return;
              }

            // otherwise log contents
            var content = buff.toString();
            content += "\n"
            content += new Date()
            content += " ["
              if (logLevel === 3) {
                content += "ERROR] <"
              } else if (logLevel === 2) {
                content += "WARN] <"
              } else if (logLevel === 1) {
                content += "INFO] <"
              } else {
                content += "INFO] <"
                console.warn("`logLevel` was either invalid or not provided.")
              }
              if (typeof source !== 'undefined') {
                content += source
                content += "> "
              } else {
                content += "unknown> "
              }
              content += message

              fs.writeFile('github-actions.log', content, err => {
                if (err) {
                  console.error("[!!! ----- logAction failed ----- !!!]")
                  console.error(err);
                }
                console.log("action logged")
                // file written successfully
              });
            });
          }
          logAction("${{ github.event.inputs.message }}", ${{ github.event.inputs.logLevel }}, "CONSOLE")
          core.notice("${{ github.event.inputs.message }}")
          try {
            var tools = require("./logAction.js")
          } catch (ERR) {
            if (ERR) {
              console.error(ERR)
            } else {
              console.log(tools)
            }
          }
    - name: push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "logged message init by gh-actions-log"
        git push
